# Generated by Django 5.0.1 on 2024-11-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShortenerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
