# Generated by Django 5.0.1 on 2024-11-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShortenerApp', '0002_alter_url_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='username',
            field=models.CharField(default='anonymous', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='url',
            unique_together={('username', 'code')},
        ),
    ]
